apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  redis-host: "redis-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  username: cHJvZHVzZXI= # 'produser'를 base64로 인코딩
  password: cHJvZHNlY3JldA== # 'prodsecret'를 base64로 인코딩
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MyApp
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
        - name: my-container
          image: node-server:2
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 3000
