apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  hostname: "prod-db.example.com"
  username: "prod-user"
  password: "prod-pass"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
